/**
 * Revenue Skill Handlers
 *
 * Three x402-gated skill endpoints that generate revenue for the automaton.
 * Each handler follows the same pattern:
 *   1. Look up tier config from pricing
 *   2. Verify x402 payment
 *   3. Process request (STUB business logic)
 *   4. Log revenue
 *   5. Estimate and log expense
 *   6. Return SkillResponse
 */

import type BetterSqlite3 from "better-sqlite3";
import { ulid } from "ulid";
import type { SkillRequest, SkillResponse, PricingConfig } from "./types.js";
import { verifyPayment, recordRevenue, recordExpense } from "./payment-gate.js";

type Database = BetterSqlite3.Database;

/**
 * /summarize-basic -- High-volume, low-ticket summarization
 * Price: $0.25 | Model: claude-3-5-haiku-20241022 | Max input: 4K tokens
 *
 * STUB: Returns a placeholder summary. In production, this would
 * call the inference client with claude-3-5-haiku-20241022 to generate a concise
 * summary of the input content.
 */
export async function handleSummarizeBasic(
  db: Database,
  request: SkillRequest,
  pricing: PricingConfig,
): Promise<SkillResponse> {
  const tier = "summarize-basic";
  const tierConfig = pricing.tiers[tier];
  const requestId = ulid();

  if (!tierConfig) {
    return {
      success: false,
      tier,
      error: `Tier "${tier}" not found in pricing configuration`,
      requestId,
      estimatedCostCents: 0,
    };
  }

  // Step 1: Verify x402 payment
  const payment = verifyPayment(request.paymentProof, tierConfig.price_usd);
  if (!payment.verified) {
    return {
      success: false,
      tier,
      error: payment.error,
      requestId,
      estimatedCostCents: 0,
    };
  }

  // Step 2: Estimate input tokens (rough: content.length / 4)
  const inputTokensEstimate = Math.ceil(request.content.length / 4);

  // Step 3: Check input token limit
  if (inputTokensEstimate > tierConfig.max_input_tokens) {
    return {
      success: false,
      tier,
      error: `Input too large: ~${inputTokensEstimate} tokens exceeds ${tierConfig.max_input_tokens} token limit for ${tier}`,
      requestId,
      estimatedCostCents: 0,
    };
  }

  // Step 4: STUB business logic -- generate placeholder summary
  const result = `[STUB] Summary of ${request.content.length} chars for tier ${tier}. ` +
    `Model: ${tierConfig.model}, estimated tokens: ${inputTokensEstimate}. ` +
    `In production, this would return a concise summary generated by ${tierConfig.model}.`;

  // Step 5: Log revenue (price in cents)
  const amountCents = Math.round(tierConfig.price_usd * 100);
  recordRevenue(db, {
    tier,
    amountCents,
    requestId,
    nicheId: request.nicheId,
    experimentId: request.experimentId,
    paymentProof: request.paymentProof,
  });

  // Step 6: Estimate and log expense
  const estimatedCostCents = recordExpense(db, {
    tier,
    model: tierConfig.model,
    inputTokensEstimate,
    requestId,
    nicheId: request.nicheId,
    experimentId: request.experimentId,
  });

  return {
    success: true,
    tier,
    result,
    requestId,
    estimatedCostCents,
  };
}

/**
 * /brief-standard -- Mid-ticket structured brief
 * Price: $2.50 | Model: claude-3-5-haiku-20241022 | Max input: 16K tokens
 *
 * STUB: Returns a placeholder brief. In production, this would call
 * claude-3-5-haiku-20241022 with a structured prompt to generate a brief containing
 * key findings, risks, and recommendations.
 */
export async function handleBriefStandard(
  db: Database,
  request: SkillRequest,
  pricing: PricingConfig,
): Promise<SkillResponse> {
  const tier = "brief-standard";
  const tierConfig = pricing.tiers[tier];
  const requestId = ulid();

  if (!tierConfig) {
    return {
      success: false,
      tier,
      error: `Tier "${tier}" not found in pricing configuration`,
      requestId,
      estimatedCostCents: 0,
    };
  }

  // Step 1: Verify x402 payment
  const payment = verifyPayment(request.paymentProof, tierConfig.price_usd);
  if (!payment.verified) {
    return {
      success: false,
      tier,
      error: payment.error,
      requestId,
      estimatedCostCents: 0,
    };
  }

  // Step 2: Estimate input tokens (rough: content.length / 4)
  const inputTokensEstimate = Math.ceil(request.content.length / 4);

  // Step 3: Check input token limit
  if (inputTokensEstimate > tierConfig.max_input_tokens) {
    return {
      success: false,
      tier,
      error: `Input too large: ~${inputTokensEstimate} tokens exceeds ${tierConfig.max_input_tokens} token limit for ${tier}`,
      requestId,
      estimatedCostCents: 0,
    };
  }

  // Step 4: STUB business logic -- generate placeholder brief
  const result = `[STUB] Structured brief of ${request.content.length} chars for tier ${tier}. ` +
    `Model: ${tierConfig.model}, estimated tokens: ${inputTokensEstimate}. ` +
    `In production, this would return a structured brief with key findings, ` +
    `risks, and recommendations generated by ${tierConfig.model}.`;

  // Step 5: Log revenue (price in cents)
  const amountCents = Math.round(tierConfig.price_usd * 100);
  recordRevenue(db, {
    tier,
    amountCents,
    requestId,
    nicheId: request.nicheId,
    experimentId: request.experimentId,
    paymentProof: request.paymentProof,
  });

  // Step 6: Estimate and log expense
  const estimatedCostCents = recordExpense(db, {
    tier,
    model: tierConfig.model,
    inputTokensEstimate,
    requestId,
    nicheId: request.nicheId,
    experimentId: request.experimentId,
  });

  return {
    success: true,
    tier,
    result,
    requestId,
    estimatedCostCents,
  };
}

/**
 * /brief-premium -- Low-volume, high-ticket deep dive
 * Price: $15.00 | Model: claude-sonnet-4-20250514 | Max input: 64K tokens
 *
 * STUB: Returns a placeholder deep-dive analysis. In production,
 * this would call claude-sonnet-4-20250514 with an extensive structured prompt to
 * produce a deep-dive analysis with competitive landscape and
 * strategic recommendations.
 */
export async function handleBriefPremium(
  db: Database,
  request: SkillRequest,
  pricing: PricingConfig,
): Promise<SkillResponse> {
  const tier = "brief-premium";
  const tierConfig = pricing.tiers[tier];
  const requestId = ulid();

  if (!tierConfig) {
    return {
      success: false,
      tier,
      error: `Tier "${tier}" not found in pricing configuration`,
      requestId,
      estimatedCostCents: 0,
    };
  }

  // Step 1: Verify x402 payment
  const payment = verifyPayment(request.paymentProof, tierConfig.price_usd);
  if (!payment.verified) {
    return {
      success: false,
      tier,
      error: payment.error,
      requestId,
      estimatedCostCents: 0,
    };
  }

  // Step 2: Estimate input tokens (rough: content.length / 4)
  const inputTokensEstimate = Math.ceil(request.content.length / 4);

  // Step 3: Check input token limit
  if (inputTokensEstimate > tierConfig.max_input_tokens) {
    return {
      success: false,
      tier,
      error: `Input too large: ~${inputTokensEstimate} tokens exceeds ${tierConfig.max_input_tokens} token limit for ${tier}`,
      requestId,
      estimatedCostCents: 0,
    };
  }

  // Step 4: STUB business logic -- generate placeholder deep-dive
  const result = `[STUB] Deep-dive analysis of ${request.content.length} chars for tier ${tier}. ` +
    `Model: ${tierConfig.model}, estimated tokens: ${inputTokensEstimate}. ` +
    `In production, this would return a comprehensive analysis with ` +
    `competitive landscape and strategic recommendations generated by ${tierConfig.model}.`;

  // Step 5: Log revenue (price in cents)
  const amountCents = Math.round(tierConfig.price_usd * 100);
  recordRevenue(db, {
    tier,
    amountCents,
    requestId,
    nicheId: request.nicheId,
    experimentId: request.experimentId,
    paymentProof: request.paymentProof,
  });

  // Step 6: Estimate and log expense
  const estimatedCostCents = recordExpense(db, {
    tier,
    model: tierConfig.model,
    inputTokensEstimate,
    requestId,
    nicheId: request.nicheId,
    experimentId: request.experimentId,
  });

  return {
    success: true,
    tier,
    result,
    requestId,
    estimatedCostCents,
  };
}
